//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ასაკის მინიმუმი ზღვარი - 18 წელი.
        /// </summary>
        public static string EighteenYearsError {
            get {
                return ResourceManager.GetString("EighteenYearsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მოცემული ველი სავალდებულოა შეიცავდეს მაქსიმუმ 50 სიმბოლოს.
        /// </summary>
        public static string MaxLengthError {
            get {
                return ResourceManager.GetString("MaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მოცემული ველი სავალდებულოა შეიცავდეს მინიმუმ 2 სიმბოლოს.
        /// </summary>
        public static string MinLengthError {
            get {
                return ResourceManager.GetString("MinLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ტელეფონის ნომერი უნდა იყოს შემდეგი ტიპიდან ერთერთი(სახლის-1, ოფისის-2, მობილური-3).
        /// </summary>
        public static string PhoneNumberError {
            get {
                return ResourceManager.GetString("PhoneNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პირადი ნომერი უნდა შედგებოდეს 11 სიმბოლოსგან.
        /// </summary>
        public static string PrivateNumberLengthError {
            get {
                return ResourceManager.GetString("PrivateNumberLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დაკავშირებული პერსონა უნდა იყოს შემდეგი ტიპის (კოლეგა-1, ნაცნობი-2, ნათესავი-3,სხვა-4).
        /// </summary>
        public static string RelatedPersonValidation {
            get {
                return ResourceManager.GetString("RelatedPersonValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მოცემული ველი სავალდებულოა.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სქესი შეიძლება იყოს მხოლოდ მამაკაცი-1 ან ქალი-2.
        /// </summary>
        public static string SexError {
            get {
                return ResourceManager.GetString("SexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to არასწორი ფორმატი(მხოლოდ ქართული ან მხოლოდ ლათინური სიმბოლოები!).
        /// </summary>
        public static string WrongFormat {
            get {
                return ResourceManager.GetString("WrongFormat", resourceCulture);
            }
        }
    }
}
